version: '3'

volumes:
  mysql-volume:

services:
  web:
    image: nginx 
    container_name: web
    depends_on:
      - vue
      - api
    ports:
      - 80:80 
    volumes:
      - ./vue:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  vue:
    build: ./docker/vue
    container_name: vue
    volumes:
      - ./vue:/app
    tty: true
    working_dir: /app

  api:
    container_name: api  
    build: ./docker/api
    volumes:
      - ./api:/var/www/api
